node {

    def app
    stage('GitCheckout') {
        // Cloning project microservices-demo
        // checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'jx-pipeline-git-github-github', url: 'https://github.com/jx-grmef-test/microservices-demo.git']]])

        checkout scm

        sh 'pwd && ls -l && ls -l release'
    }
    stage('Initialize') {
        def dockerHome = tool 'Docker-19'
        env.PATH = "${dockerHome}/bin:${env.PATH}"

        sh 'docker -v'

    }
    stage('Build image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */
        dir("src/adservice") {
            sh "pwd"
            app = docker.build("microservices-demo/image/adservice")
        }

        dir("src/cartservice") {
            sh "pwd"
            app = docker.build("microservices-demo/image/cartservice")
        }

        dir("src/checkoutservice") {
            sh "pwd"
            app = docker.build("microservices-demo/image/checkoutservice")
        }

        dir("src/currencyservice") {
            sh "pwd"
            app = docker.build("microservices-demo/image/currencyservice")
        }

        dir("src/emailservice") {
            sh "pwd"
            app = docker.build("microservices-demo/image/emailservice")
        }

        dir("src/frontend") {
            sh "pwd"
            app = docker.build("microservices-demo/image/frontend")
        }

        dir("src/loadgenerator") {
            sh "pwd"
            app = docker.build("microservices-demo/image/loadgenerator")
        }

        dir("src/paymentservice") {
            sh "pwd"
            app = docker.build("microservices-demo/image/paymentservice")
        }

        dir("src/productcatalogservice") {
            sh "pwd"
            app = docker.build("microservices-demo/image/productcatalogservice")
        }

        dir("src/recommendationservice") {
            sh "pwd"
            app = docker.build("microservices-demo/image/recommendationservice")
        }

        dir("src/shippingservice") {
            sh "pwd"
            app = docker.build("microservices-demo/image/shippingservice")
        }

        stage('Test image') {
            /* We test our image with a simple smoke test:
             * Run a curl inside the newly-build Docker image */

            sh "echo $PATH"
            docker.image("microservices-demo/image/adservice:latest").inside("--entrypoint=''") { c ->
                //sh 'curl http://localhost:9555 || exit 1'
                sh 'find / -type f -name AdService'
                sh 'cat /app/build/install/hipstershop/bin/AdService'
                sh 'echo "Tests passed"'
            }

            docker.image("microservices-demo/image/cartservice:latest").inside("--entrypoint=''") { c ->
                //sh 'curl http://localhost:7070 || exit 1'
                sh 'find / -type f -name cartservice'
                // sh 'cat /app/cartservice'
                sh 'echo "Tests passed"'
            }

            docker.image("microservices-demo/image/checkoutservice:latest").inside("--entrypoint=''") { c ->
                //sh 'curl http://localhost:5050 || exit 1'
                sh 'find / -type f -name checkoutservice'
                // sh 'cat /app/cartservice'
                sh 'echo "Tests passed"'
            }

            docker.image("microservices-demo/image/currencyservice:latest").inside("--entrypoint=''") { c ->
                //sh 'curl http://localhost:7000 || exit 1'
                sh 'which node'
                sh 'find / -type f -name server.js'
                // sh 'cat /'
                sh 'echo "Currency Service Test passed"'
            }

            docker.image("microservices-demo/image/emailservice:latest").inside("--entrypoint=''") { c ->
                //sh 'curl http://localhost:5000 || exit 1'
                sh 'which python'
                sh 'find / -type f -name email_server.py'
                // sh 'cat /app/cartservice'
                sh 'echo "Tests passed"'
            }

            docker.image("microservices-demo/image/frontend:latest").inside("--entrypoint=''") { c ->
                //sh 'curl http://localhost:8080 || exit 1'
                sh 'find / -type f -name server'
                //sh 'cat /frontend/server'
                sh 'echo "Tests passed"'
            }

            docker.image("microservices-demo/image/loadgenerator:latest").inside("--entrypoint=''") { c ->
                //sh 'curl http://localhost:80 || exit 1'
                sh 'find / -type f -name loadgen.sh'
                //sh 'cat ./loadgen.sh'
                sh 'echo "Tests passed"'
            }

            docker.image("microservices-demo/image/paymentservice:latest").inside("--entrypoint=''") { c ->
                //sh 'curl http://localhost:50051 || exit 1'
                sh 'which node'
                sh 'find / -type f -name index.js'
                //sh 'cat '
                sh 'echo "Tests passed"'
            }

            docker.image("microservices-demo/image/productcatalogservice:latest").inside("--entrypoint=''") { c ->
                //sh 'curl http://localhost:3550 || exit 1'
                sh 'find / -type f -name server'
                //sh 'cat /productcatalogservice/server'
                sh 'echo "Tests passed"'
            }

            docker.image("microservices-demo/image/recommendationservice:latest").inside("--entrypoint=''") { c ->
                //sh 'curl http://localhost:8080 || exit 1'
                sh 'find / -type f -name recommendation_server.py'
                //sh 'cat /'
                sh 'echo "Tests passed"'
            }

            docker.image("microservices-demo/image/shippingservice:latest").inside("--entrypoint=''") { c ->
                //sh 'curl http://localhost:50051 || exit 1'
                sh 'find / -type f -name shippingservice'
                //sh 'cat /'
                sh 'echo "Tests passed"'
            }
        }
        stage('Push image to Nexus') {
            /* Finally, we'll push the image with two tags:
             * First, the incremental build number from Jenkins
             * Second, the 'latest' tag.
             * Pushing multiple tags is cheap, as all the layers are reused. */
            docker.withRegistry('http://nexus-docker.apps.meflab.xyz/repository/microservices-demo/', 'nexus-password') {
                app.push("${env.BUILD_NUMBER}")
                app.push("latest")
            }
        }
        stage('Remove Unused docker image') {
            //sh "docker rmi $registry:$BUILD_NUMBER"
            //sh 'docker rmi $(docker images --filter=reference="http://nexus-docker.apps.meflab.xyz/repository/microservices-demo/shippingservice*" -q)'
        }
    }
}